server:
  port: 8888
spring:
  application:
    name: config-server-prod
  cloud:
    config:
      server:
        composite:
          -
            type: couchbase
            connectionString: couchbase://127.0.0.1
            userName: userName1
            password: Password1
            configBucketName: configuration-store
            scope: technical
            collectionName: application-properties
            order: 1
    bus:
      enabled: true
      id: my-config-server
      destination: manuallycreatedtopic
    stream:
      kafka:
        binder:
          autoCreateTopics: false
          zkNodes:  localhost:2181
          brokers: localhost:29092
          consumer-properties:
            allow:
              auto:
                create:
                  topics: false
management:
  endpoints:
    web:
      exposure:
        include:  health, busrefresh, bus-env, refresh, env
  endpoint:
    info:
      enabled: true
logging:
  level:
    ROOT: ERROR
    com.sannette.eis.mega.*: INFO
    org.apache.kafka.*: INFO