server:
  port: 8082

spring:
  application:
    name: notification-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
  logging:
    level:
      com.vignette.eis.mega.*: ERROR
  cloud:
    bus:
      enabled: true
      destination: myownmanuallycreatedtopic
    stream:
      kafka:
        binder:
          autoCreateTopics: false
          zkNodes: localhost:2181
          brokers: localhost:29092
management:
  endpoints:
    web:
      exposure:
        include:  health, busrefresh, bus-env, refresh, env
  endpoint:
    info:
      enabled: true