server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/santhosh34/spring-cloud-config-store.git
          searchPaths: '{application}/{profile}'
